stages:
  - build
  - docker

variables:
  DOCKER_IMAGE: "paradoxhorizondevs/save-money-api"
  TAG: $CI_COMMIT_REF_SLUG
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - target

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21-noble
  script:
    - mvn clean package
  artifacts: # pass artifacts to next stage
    paths:
      - target/*.jar
      - Dockerfile
    untracked: false
    when: on_success
    access: all
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  # Run only on main branch

docker-build-push:
  stage: docker
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_BUILDKIT: 1 # Enable BuildKit for better secret handling
  dependencies:
    - build # Fetch artifacts from build stage
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build --build-arg AUTH_URL=$AUTH_URL --build-arg AUTH_API_KEY=$AUTH_API_KEY --build-arg SUPABASE_DB_URL=$SUPABASE_DB_URL --build-arg SUPABASE_API_KEY=$SUPABASE_API_KEY -t $DOCKER_IMAGE:$TAG .
    - docker push $DOCKER_IMAGE:$TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  # Run only on main branch